# Environment where the service is running
env: local

# Listening port of the serivce
http:
  port: "8081"
  
ftp:
  host: myhost
  username: myuser
  password: mypassword
  directoryinput: in
  directoryoutput: out
