CREATE TABLE demodb.TAX_PAYER (
	ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	FIRST_NAME VARCHAR(100),
	LAST_NAME VARCHAR(100),
	TYPE_TIN VARCHAR(100),
	TIN VARCHAR(100),
	PRIMARY KEY (ID)
);